### ISSUE TITLE
hi max

### ISSUE THREAD

**Issue by doged** [MaxLaumeister/bitlisten#15]
i was trying to set this up via websocket on the insight explorer.. it uses socket.io, served from 
/socket.io/  ie: https://insight.bitpay.com/socket.io/?EIO=2&transport=websocket&sid=45phrp2GEjPdrlOgABKU

for some reason when i replace the wss://bitcoin.toshi.io with wss://insight.bitpay.com/socket.io/ it doesnt connect. im very familiar with nodejs, but not using websockets.  im guessing my address syntax is off. 

care to lend some advice?

ive tried
wss://insight.bitpay.com/socket.io/inv/
and
wss://insight.bitpay.com/socket.io/

but im not getting anywhere. ill tip for your time. thanks =]

**Comment by lupine-dev** [comment]
Hi doged,

As far as I can tell, insight cannot accept websocket connections directly - you must use the Socket.io javascript library to initiate and manage a connection. Here is their example from the [Insight Readme](https://github.com/bitpay/insight-api):

```
<html>
<body>
  <script src="http://<insight-server>:<port>/socket.io/socket.io.js"></script>
  <script>
    eventToListenTo = 'tx'
    room = 'inv'

    var socket = io("http://<insight-server>:<port>/");
    socket.on('connect', function() {
      // Join the room.
      socket.emit('subscribe', room);
    })
    socket.on(eventToListenTo, function(data) {
      console.log("New transaction received: " + data.txid)
    })
  </script>
</body>
</html>
```

As you can see, instead of using the websocket's "onmessage" method, the socket.io object has "on" method that takes an event name as a parameter ([socket.io docs here](http://socket.io/docs/)). There are probably some other minor changes to the socket code needed to get it working with socket.io.

Also if I remember correctly, Bitpay's Insight server does not allow cross-origin resource sharing (CORS) so you will not actually be able to connect to their server from a web page, though they might have changed that since I last checked (AFAIK the idea according to them is to host your own Insight server instead of relying on theirs).

**Comment by doged** [comment]
yeah i had that in my index.html, just wasnt sure on what to do in bitlisten.min.js, as far as passing the connection from the index.html page

**Comment by doged** [comment]
i built a new insight explorer yesterday, but still cannot figure out how to modify the bitlisten.min.js to get it to listen to the socket.io

**Comment by lupine-dev** [comment]
> i had that in my index.html

You will actually need to work that socket.io code into socket.js (replacing the websocket code that's already there), and then rebuild bitlisten.min.js. So in your index.html you include socket.io.js then bitlisten.min.js, and the only other modification you need to make to get the sockets working is to socket.js.
